<a href="https://colab.research.google.com/github/saim9211/Machine-Learning-Stuff/blob/main/Handling_mixed_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [19]:
df=pd.read_csv('titanic.csv')

In [20]:
df.sample(3)

    Cabin  Ticket number  Survived
383   NaN  113789      4         1
81    NaN  345779      6         1
296   NaN    2693      4         0

In [21]:
df['number_int'] = pd.to_numeric(df['number'].str.extract('(\\d+)')[0], errors='coerce')

In [22]:
df['number_Str'] = df['number'].str.extract(r'([^\d]+)')[0]

In [23]:
df['number_int'].fillna(0, inplace=True)

/tmp/ipykernel_21919/1070211411.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['number_int'].fillna(0, inplace=True)

In [24]:
df['Cabin_int'] = pd.to_numeric(df['Cabin'].str.extract('(\\d+)')[0], errors='coerce')
df['Cabin_Str'] = df['Cabin'].str.extract(r'([A-Za-z]+)')[0]

In [25]:
df.head()

,Cabin,Ticket,number,Survived,number_int,number_Str,Cabin_int,Cabin_Str
0,NaN,A/5 21171,5,0,5.0,NaN,NaN,NaN
1,C85,PC 17599,3,1,3.0,NaN,85.0,C
2,NaN,STON/O2. 3101282,6,1,6.0,NaN,NaN,NaN
3,C123,113803,3,1,3.0,NaN,123.0,C
4,NaN,373450,A,0,0.0,A,NaN,NaN

In [26]:
df['Ticket_int'] = pd.to_numeric(df['Ticket'].str.extract('(\\d+)')[0], errors='coerce')
df['Ticket_Str'] = df['Ticket'].str.extract(r'([^\\d]+)')[0]

In [27]:
df

,Cabin,Ticket,number,Survived,number_int,number_Str,Cabin_int,Cabin_Str,Ticket_int,Ticket_Str
0,NaN,A/5 21171,5,0,5.0,NaN,NaN,NaN,5.0,A/5 21171
1,C85,PC 17599,3,1,3.0,NaN,85.0,C,17599.0,PC 17599
2,NaN,STON/O2. 3101282,6,1,6.0,NaN,NaN,NaN,2.0,STON/O2. 3101282
3,C123,113803,3,1,3.0,NaN,123.0,C,113803.0,113803
4,NaN,373450,A,0,0.0,A,NaN,NaN,373450.0,373450
...,...,...,...,...,...,...,...,...,...,...
886,NaN,211536,3,0,3.0,NaN,NaN,NaN,211536.0,211536
887,B42,112053,3,1,3.0,NaN,42.0,B,112053.0,112053
888,NaN,W./C. 6607,1,0,1.0,NaN,NaN,NaN,6607.0,W./C. 6607
889,C148,111369,2,1,2.0,NaN,148.0,C,111369.0,111369
890,NaN,370376,3,0,3.0,NaN,NaN,NaN,370376.0,370376

In [28]:
df2=pd.read_csv('orders.csv')
df3=pd.read_csv('messages.csv')

In [29]:
df2.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [30]:
df2['date'] = pd.to_datetime(df2['date'])
df2['year'] = df2['date'].dt.year
df2['month'] = df2['date'].dt.month
df2['day'] = df2['date'].dt.day
df2['month_name'] = df2['date'].dt.month_name()
df2['day_name'] = df2['date'].dt.day_name()

In [31]:
df2

,date,product_id,city_id,orders,year,month,day,month_name,day_name
0,2019-12-10,5628,25,3,2019,12,10,December,Tuesday
1,2018-08-15,3646,14,157,2018,8,15,August,Wednesday
2,2018-10-23,1859,25,1,2018,10,23,October,Tuesday
3,2019-08-17,7292,25,1,2019,8,17,August,Saturday
4,2019-01-06,4344,25,3,2019,1,6,January,Sunday
...,...,...,...,...,...,...,...,...,...
995,2018-10-08,255,13,1,2018,10,8,October,Monday
996,2018-12-06,5521,7,1,2018,12,6,December,Thursday
997,2019-05-07,487,26,14,2019,5,7,May,Tuesday
998,2019-03-03,1503,21,2,2019,3,3,March,Sunday
999,2019-10-15,6371,7,22,2019,10,15,October,Tuesday

In [32]:
df3.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [33]:
df3['date'] = pd.to_datetime(df3['date'])
df3['year'] = df3['date'].dt.year
df3['month'] = df3['date'].dt.month
df3['day'] = df3['date'].dt.day
df3['hour'] = df3['date'].dt.hour
df3['minute'] = df3['date'].dt.minute
df3['second'] = df3['date'].dt.second
df3['month_name']=df3['date'].dt.month_name()
df3['day_name']=df3['date'].dt.day_name()

In [34]:
df3.head()

,date,msg,year,month,day,hour,minute,second,month_name,day_name
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,2013,12,15,0,50,0,December,Sunday
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,2014,4,29,23,40,0,April,Tuesday
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,2012,12,30,0,21,0,December,Sunday
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,2014,11,28,0,31,0,November,Friday
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,2013,10,26,23,11,0,October,Saturday