<a href="https://colab.research.google.com/github/saim9211/Machine-Learning-Stuff/blob/main/pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
df=pd.read_csv("train.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [12]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [13]:
df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier

In [22]:
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns="Survived"),df['Survived'],test_size=0.3,random_state=42)
x_train.shape,x_test.shape

((623, 7), (268, 7))

In [31]:
x_train.head()

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
445       1    male   4.0      0      2  81.8583        S
650       3    male   NaN      0      0   7.8958        S
172       3  female   1.0      1      1  11.1333        S
450       2    male  36.0      1      2  27.7500        S
314       2    male  43.0      1      1  26.2500        S

In [23]:
tf1=Pipeline([
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('ohe',OneHotEncoder())
])

In [24]:
tf2=Pipeline([
    ('imputer',SimpleImputer(strategy='mean')),
    ('scaler',StandardScaler())
])

In [32]:
from scipy import sparse
tf3=Pipeline([
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('hot_coding',OneHotEncoder(sparse_output=False),[1,6])
])

In [33]:
tf4=Pipeline(
    [
        ('impute',SimpleImputer(strategy='mean')),
        ('ordinary_coding',OrdinalEncoder(categories=[['S','C','Q']]),[6])
    ]
)

In [34]:
from sklearn.preprocessing import MinMaxScaler
tf5=Pipeline(
    [
        ('impute',SimpleImputer()),
        ('min_max',MinMaxScaler())

    ]
)

In [43]:
tf6 = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),

    ('classifier', DecisionTreeClassifier())
])